Repository DEFRA/water-abstraction-ui, pull requests merged in 2022-08, with the labels that each got.

#2170 Update release process
  package.json
Labels: enhancement

#2172 The charge ref is incorrect in the transaction detail
  src/internal/modules/billing/lib/mappers.js
  src/internal/modules/billing/services/transactions-csv.js
  src/internal/views/nunjucks/billing/macros/transactions-table-sroc.njk
  src/shared/lib/number-formatter.js
  src/shared/view/nunjucks/filters/charge.js
  test/shared/lib/number-formatter.js
  test/shared/view/nunjucks/filters/charge.js
Labels: bug

#2174 Hide `standard` linting commit with `.git-blame-ignore-revs`
  .git-blame-ignore-revs
Labels: enhancement, housekeeping

#2176 Fix Notify callback exception
  src/external/modules/notify/controller.js
  test/external/modules/notify/controller.js
Labels: bug

#2177 Add logging to failed Notify callback
  src/external/modules/notify/controller.js
Labels: bug

#2178 Change logging level for Notify callback
  src/external/modules/notify/controller.js
Labels: housekeeping

#2179 Make charge version max upload consistent
  src/external/modules/returns/routes/upload.js
  src/internal/modules/charge-information-upload/routes.js
Labels: housekeeping

#2180 Hide big tech debt change with git blame ignore
  .git-blame-ignore-revs
Labels: housekeeping

#2181 Set log level using new env var
  .env.example
  src/external/config.js
  src/internal/config.js
Labels: housekeeping

#2189 TPT adjustment not being displayed in transaction detail
  src/internal/modules/billing/lib/mappers.js
  test/internal/modules/billing/lib/mappers.js
Labels: bug

#2190 Correctly set NODE_ENV
  .env.example
  src/external/config.js
  src/external/lib/view-engine/index.js
  src/external/lib/view.js
  src/internal/config.js
  src/internal/lib/view-engine/index.js
  src/internal/lib/view.js
  src/shared/plugins/acceptance-tests-proxy/routes.js
  src/shared/plugins/cookie-message/index.js
  test/shared/plugins/cookie-message/index.js
Labels: housekeeping
