Repository DEFRA/water-abstraction-ui, pull requests merged in 2022-07, with the labels that each got.

#2120 Tidy up .../billing/services/transactions-csv.js
  src/internal/modules/billing/services/transactions-csv.js
  test/internal/modules/billing/services/transactions-csv.js
  test/support/helpers/general.helper.js
Labels: housekeeping

#2117 Export bill run CSV file for sroc
  src/internal/modules/billing/controllers/bill-run.js
  src/internal/modules/billing/services/transactions-csv.js
  test/internal/modules/billing/controllers/bill-run.js
  test/internal/modules/billing/services/transactions-csv.js
Labels: enhancement

#2123 Apply consistent CI workflow
  .github/workflows/ci.yml
  .github/workflows/regression.yml
  .labrc.js
  README.MD
  run-test.sh
  sonar-project.properties
  statuses.md
Labels: housekeeping

#2125 Add dependabot.yml config file
  .github/dependabot.yml
Labels: housekeeping

#2134 Make gitignore consistent with other projects
  .gitignore
Labels: housekeeping

#2135 Tidy up package.json
  package.json
Labels: housekeeping

#2136 Remove snyk dev dependency
  .snyk
  package-lock.json
  package.json
Labels: housekeeping

#2143 Fix export bill run csv for sroc
  src/internal/modules/billing/services/transactions-csv.js
  test/internal/modules/billing/services/transactions-csv.js
Labels: bug

#2145 Fix Compensation Charge field in CSV export
  src/internal/modules/billing/services/transactions-csv.js
  test/internal/modules/billing/services/transactions-csv.js
Labels: bug

#2147 Rename Delete All Billing Data flag
  .env.example
  src/internal/config.js
Labels: housekeeping

#2153 Postal address issue - water abstraction alerts
  src/internal/views/nunjucks/gauging-stations/confirm-sending-alerts.njk
Labels: bug

#2155 Add `lint:fix` script to `package.json`
  package.json
Labels: housekeeping

#2156 Postal address issue - Remove separate postcode field from template
  src/internal/views/nunjucks/gauging-stations/confirm-sending-alerts.njk
Labels: enhancement, housekeeping

#2158 Addition of mBOD as a unit type in the tagging flow
  src/internal/modules/gauging-stations/forms/new-tag/threshold-and-unit.js
  src/internal/modules/gauging-stations/lib/helpers.js
  test/internal/modules/gauging-stations/lib/helpers.js
Labels: enhancement

#2159 SRoC charge creation - additional characters required in charge reference description
  src/internal/modules/charge-information/forms/charge-category/description.js
  test/internal/modules/charge-information/forms/charge-categories/description.js
Labels: enhancement

#2160 Handle 0 Volumes
  src/internal/modules/charge-information/forms/charge-category/volume.js
  test/internal/modules/charge-information/forms/charge-category/adjustments.js
  test/internal/modules/charge-information/forms/charge-category/default-radio-options-form.js
  test/internal/modules/charge-information/forms/charge-category/description.js
  test/internal/modules/charge-information/forms/charge-category/volume.js
Labels: enhancement

#2161 Handle 0 Volumes
  src/internal/modules/charge-information/forms/charge-category/volume.js
Labels: enhancement

#2162 SROC charge creation - amend hint and error
  src/internal/modules/charge-information/forms/charge-category/description.js
  test/internal/modules/charge-information/forms/charge-category/description.js
Labels: enhancement

#2163 Skip public water question page if licence holder isn't water undertaker
  src/internal/modules/charge-information/controllers/charge-category.js
  src/internal/modules/charge-information/controllers/charge-information.js
  src/internal/modules/charge-information/controllers/view-charge-information.js
  src/internal/modules/charge-information/lib/charge-categories/constants.js
  src/internal/views/nunjucks/charge-information/macros/charge-element-table-sroc.njk
  src/internal/views/nunjucks/charge-information/view.njk
  test/internal/modules/charge-information/controllers/charge-category.js
Labels: enhancement
