Repository DEFRA/water-abstraction-ui, pull requests merged in 2022-10, with the labels that each got.

#2215 Fix licence returns pagination
  src/external/views/nunjucks/returns/licence.njk
  src/internal/views/nunjucks/returns/licence.njk
Labels: bug

#2219 Licences with reduce tags appearing in the mailing list when the user…
  src/internal/modules/gauging-stations/controller.js
  test/internal/modules/gauging-stations/controller.test.js
Labels: bug

#2223 Revert changelog script change with improvements
  package.json
Labels: housekeeping

#2225 Add new /health/info endpoint
  src/external/modules/routes.js
  src/internal/modules/routes.js
  src/shared/modules/health/controller.js
  src/shared/modules/health/routes.js
  test/shared/modules/health/controller.test.js
Labels: enhancement

#2213 Fix acceptance-tests proxy
  src/external/lib/connectors/services/water/index.js
  src/external/lib/hapi-plugins/index.js
  src/internal/config.js
  src/internal/lib/connectors/services/water/AcceptanceTestsProxyService.js
  src/internal/lib/connectors/services/water/index.js
  src/internal/lib/hapi-plugins/index.js
  src/internal/modules/acceptance-tests-proxy/controller.js
  src/internal/modules/acceptance-tests-proxy/routes.js
  src/internal/modules/routes.js
  src/shared/plugins/acceptance-tests-proxy/controller.js
  src/shared/plugins/acceptance-tests-proxy/index.js
  test/internal/modules/acceptance-tests-proxy/controller.test.js
  test/internal/modules/acceptance-tests-proxy/routes.test.js
Labels: bug
