Repository DEFRA/water-abstraction-ui, pull requests merged in 2022-11, with the labels that each got.

#2229 Create system proxy endpoint
  .env.example
  src/internal/config.js
  src/internal/lib/connectors/services/water/SystemProxyService.js
  src/internal/modules/routes.js
  src/internal/modules/system-proxy/controller.js
  src/internal/modules/system-proxy/routes.js
  test/internal/modules/system-proxy/controller.test.js
  test/internal/modules/system-proxy/routes.test.js
Labels: enhancement

#2234 Add feature flag to fix verification code appearing in production environment
  .env.example
  src/external/config.js
  src/external/lib/view.js
  src/external/views/nunjucks/add-licences/verification-sent.njk
  src/internal/config.js
  src/internal/lib/view.js
  src/internal/views/nunjucks/add-licences/verification-sent.njk
Labels: bug

#2235 Fix request.logout() is undefined error
  src/shared/plugins/auth/index.js
  test/shared/lib/plugins/auth/index.test.js
  test/shared/plugins/auth/index.test.js
Labels: bug

#2217 Stop passing err to logger.error
  server-external.js
  server-internal.js
  src/external/lib/connectors/services/water/NotificationsApiClient.js
  src/external/modules/manage-licences/controller.js
  src/internal/modules/billing-accounts/controllers/select-billing-account.js
  src/internal/modules/service-status/controller.js
  src/internal/modules/waiting/controller.js
  src/shared/lib/connectors/services/water/NotificationsApiClient.js
  src/shared/lib/logger-factory.js
  test/external/lib/connectors/services/water/NotificationsApiClient.test.js
  test/internal/modules/billing-accounts/controllers/select-billing-account.test.js
  test/shared/lib/logger-factory.test.js
Labels: housekeeping

#2240 Remove pm2 watch config from ecosystem file
  ecosystem.config.json
Labels: housekeeping

#2244 Update water-abstraction-helpers to latest version
  package-lock.json
  package.json
Labels: dependencies

#2243 Autobuild assets after npm ci
  package.json
Labels: housekeeping
