Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-11, with the labels that each got.

#2463 Add cookie to http requests to system
  src/internal/lib/connectors/services/system/BillRunsApiClient.js
  src/internal/lib/connectors/services/system/BillingAccountsApiClient.js
  src/internal/modules/billing-accounts/controllers/select-billing-account.js
  src/internal/modules/billing/controllers/create-bill-run.js
  test/internal/modules/billing-accounts/controllers/select-billing-account.test.js
  test/internal/modules/billing/controllers/create-bill-run.test.js
Labels: enhancement

#2467 Remove charging forecast reports from UI
  src/internal/lib/connectors/services/water/ReportingService.js
  src/internal/lib/connectors/services/water/index.js
  src/internal/modules/manage/lib/manage-nav.js
  src/internal/modules/reporting/controllers.js
  src/internal/modules/reporting/routes.js
  src/internal/modules/routes.js
  src/internal/views/nunjucks/reporting/charging-forecast-reports.njk
  test/internal/lib/connectors/services/water/ReportingService.test.js
  test/internal/modules/reporting/controllers.test.js
  test/internal/modules/reporting/routes.test.js
Labels: housekeeping

#2466 Update Bill Run Trigger pages for SRoC 2PT
  .env.example
  src/internal/config.js
  src/internal/lib/connectors/services/system/BillRunsApiClient.js
  src/internal/modules/billing/controllers/create-bill-run.js
  test/internal/lib/connectors/services/system/BillRunsApiClient.test.js
  test/internal/modules/billing/controllers/create-bill-run.test.js
Labels: enhancement

#2468 Prevent SROC 2PT being triggered when FYE < 2023
  src/internal/modules/billing/controllers/create-bill-run.js
  test/internal/modules/billing/controllers/create-bill-run.test.js
Labels: enhancement

#2465 Link SROC 2PT bill runs in UI to new SROC review page
  src/internal/modules/billing/lib/routing.js
  test/internal/modules/billing/lib/routing.test.js
Labels: enhancement

#2472 Link to new bill page from all sent bills page
  src/internal/modules/view-licences/controller.js
  src/internal/views/nunjucks/billing/bills.njk
Labels: housekeeping

#2474 Make bill run summary page backlink fixed
  src/internal/modules/billing/controllers/bill-run.js
  test/internal/modules/billing/controllers/bill-run.test.js
Labels: bug
