Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-09, with the labels that each got.

#2424 Prevent double button click for send notification for licence renewals
  src/internal/views/nunjucks/notifications/preview.njk
Labels: enhancement

#2426 Redirect /service-status to system app
  src/internal/modules/service-status/controller.js
  test/internal/modules/service-status/controller.test.js
Labels: housekeeping

#2430 Fix service status redirect to system
  src/internal/modules/service-status/controller.js
  test/internal/modules/service-status/controller.test.js
Labels: bug

#2423 Send change address requests to system in future
  src/internal/lib/connectors/services/system/BillRunsApiClient.js
  src/internal/lib/connectors/services/system/BillingAccountsApiClient.js
  src/internal/lib/connectors/services/system/index.js
  src/internal/modules/billing-accounts/controllers/select-billing-account.js
  test/internal/lib/connectors/services/system/BillRunsApiClient.test.js
  test/internal/lib/connectors/services/system/BillingAccountsApiClient.test.js
  test/internal/modules/billing-accounts/controllers/select-billing-account.test.js
Labels: enhancement

#2440 Upgrade to Node 20
  .github/workflows/ci.yml
  .nvmrc
Labels: housekeeping
