Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-03, with the labels that each got.

#2303 Fix licence holder display bug 4 date of transfer
  src/internal/modules/charge-information/controllers/charge-information.js
  src/internal/modules/charge-information/controllers/view-charge-information.js
Labels: bug

#2302 Swap out or remove Deprecated packages
  package-lock.json
  package.json
  src/internal/lib/view-engine/filters/abstraction-reform.js
  src/shared/plugins/reset-password/index.js
  src/shared/plugins/update-password/index.js
  src/shared/view/nunjucks/filters/html-decode.js
  test/support/helpers/general.helper.js
Labels: housekeeping

#2311 Make request logging configurable & change default
  src/internal/config.js
  src/shared/plugins/hapi-pino.plugin.js
Labels: housekeeping

#2314 Remove axios from acceptance tests
  cypress/integration/external/notify-callback.spec.js
  cypress/support/commands.js
  cypress/support/notifications.js
  package-lock.json
  package.json
Labels: housekeeping

#2315 Fix no address selected 500 error
  src/internal/modules/address-entry/controller.js
  src/internal/modules/address-entry/forms/select-address.js
  src/internal/modules/address-entry/routes.js
  src/shared/lib/form-handler.js
  test/internal/modules/address-entry/controller.test.js
Labels: bug

#2318 Update package `file-type` and remove `read-chunk`
  package-lock.json
  package.json
  src/shared/lib/file-check.js
Labels: housekeeping

#2322 Highlight flagged for SROC supplementary billing
  src/internal/modules/view-licences/controller.js
  src/internal/views/nunjucks/view-licences/licence.njk
  test/internal/modules/view-licences/controller.test.js
Labels: enhancement
