Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-05, with the labels that each got.

#2349 Enable cancel btn for empty & errored bill runs
  src/internal/views/nunjucks/billing/batch-empty.njk
  src/internal/views/nunjucks/billing/batch-error.njk
  src/internal/views/nunjucks/billing/macros/batch-buttons.njk
Labels: enhancement

#2350 Increase bills runs per page
  .env.example
  src/internal/config.js
  src/internal/modules/billing/controllers/bill-run.js
Labels: enhancement

#2352 Additional charges incorrect for supported sources
  src/internal/modules/billing/lib/mappers.js
Labels: bug

#2353 Add auto-merge GitHub workflow
  .github/workflows/auto-merge.yml
Labels: housekeeping

#2355 Add SROC only billing feature flag
  .env.example
  src/internal/config.js
  src/internal/modules/billing/controllers/create-bill-run.js
Labels: enhancement

#2354 Remove package `parse-domain`
  package-lock.json
  package.json
  src/shared/plugins/cookie-message/lib/cookie-domain.js
  test/shared/plugins/cookie-message/index.test.js
Labels: housekeeping
