Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-01, with the labels that each got.

#2264 Fix server-common plugins
  server-external.js
Labels: bug

#2256 Call "create bill run" endpoint for sroc supplementary
  src/internal/lib/connectors/services/index.js
  src/internal/lib/connectors/services/system/BillRunsService.js
  src/internal/lib/connectors/services/system/index.js
  src/internal/modules/billing/controllers/create-bill-run.js
  src/internal/modules/billing/lib/routing.js
  test/internal/lib/connectors/services/system/BillRunsService.test.js
  test/internal/modules/billing/controllers/create-bill-run.test.js
  test/internal/modules/billing/lib/routing.test.js
Labels: enhancement

#2267 Make /notifications/last available in non-prod
  cypress/integration/external/notify-callback.spec.js
  src/external/modules/notifications/api-controller.js
  src/external/modules/notifications/routes.js
  src/external/modules/routes.js
  src/internal/modules/notifications/routes.js
  test/external/modules/notifications/controller.test.js
  test/internal/modules/notifications/controller.test.js
Labels: bug

#2266 Stop logging requests for robots.txt
  src/shared/lib/services/hapi-pino-ignore-request.service.js
Labels: bug

#2269 Trigger SROC supplementary bill run in parallel
  src/internal/modules/billing/controllers/create-bill-run.js
  src/internal/modules/billing/lib/routing.js
  src/internal/modules/billing/routes/create-bill-run.js
  test/internal/modules/billing/controllers/create-bill-run.test.js
  test/internal/modules/billing/lib/routing.test.js
Labels: housekeeping

#2270 Label empty bill runs as `EMPTY`
  src/internal/modules/billing/lib/routing.js
  src/shared/view/nunjucks/filters/batch-badge.js
  test/shared/view/nunjucks/filters/batch-badge.test.js
Labels: enhancement

#2271 Support new queued bill run status
  src/internal/modules/billing/lib/routing.js
  src/internal/modules/billing/pre-handlers.js
  src/internal/modules/billing/routes/bill-run.js
  src/internal/views/nunjucks/billing/macros/batch-buttons.njk
  src/shared/view/nunjucks/filters/batch-badge.js
  test/internal/modules/billing/routes/bill-run.test.js
Labels: enhancement

#2272 Add charge scheme annotation to bill runs page
  src/internal/views/nunjucks/billing/batch-list.njk
  test/internal/modules/billing/controllers/bill-run.test.js
Labels: enhancement

#2273 Add charge scheme to bill run view metadata
  src/internal/views/nunjucks/billing/macros/batch-metadata.njk
Labels: enhancement

#2275 Add charge scheme message to bill run spinner page
  src/internal/views/nunjucks/billing/batch-processing.njk
Labels: enhancement

#2274 Add new error page for errored bill runs
  src/internal/modules/billing/controllers/bill-run.js
  src/internal/modules/billing/lib/routing.js
  src/internal/modules/billing/pre-handlers.js
  src/internal/modules/billing/routes/bill-run.js
  src/internal/views/nunjucks/billing/batch-error.njk
  test/internal/modules/billing/controllers/bill-run.test.js
  test/internal/modules/billing/lib/routing.test.js
  test/internal/modules/billing/routes/bill-run.test.js
Labels: enhancement

#2276 Fix typo in name of repo in README
  README.MD
Labels: documentation
