Repository DEFRA/water-abstraction-ui, pull requests merged in 2023-06, with the labels that each got.

#2357 Remove package `del`
  gulpfile.js
  package-lock.json
  package.json
Labels: housekeeping

#2369 Warn the user if a bill run is 'processing'
  src/internal/modules/billing/controllers/bill-run.js
  src/internal/views/nunjucks/billing/batch-list.njk
  test/internal/modules/billing/controllers/bill-run.test.js
Labels: enhancement

#2371 Remove Cypress acceptance tests
  .gitignore
  cypress.json
  cypress/fixtures/downloads/big farm co ltd monthly return.csv
  cypress/fixtures/example.json
  cypress/fixtures/users.json
  cypress/integration/external/bulk-upload.spec.js
  cypress/integration/external/licence-alias-naming.spec.js
  cypress/integration/external/login.spec.js
  cypress/integration/external/notify-callback.spec.js
  cypress/integration/external/page-title.spec.js
  cypress/integration/external/reset-password.spec.js
  cypress/integration/external/sharing-access-with-existing-user.spec.js
  cypress/integration/external/sharing-access-with-new-user.spec.js
  cypress/integration/external/user-registration.spec.js
  cypress/integration/external/user-returns-view.spec.js
  cypress/integration/external/user-submitting-returns.spec.js
  cypress/integration/external/view-licences.spec.js
  cypress/integration/internal/billing/billing-annual-bills-run.spec.js
  cypress/integration/internal/billing/billing-cancel-bill-run.spec.js
  cypress/integration/internal/billing/billing-non-chargeable-licence-credits-back-historic-charges.spec.js
  cypress/integration/internal/billing/billing-rebilling-supplementary.spec.js
  cypress/integration/internal/billing/billing-supplementary-2part-historic-recalculate-charges.spec.js
  cypress/integration/internal/billing/billing-two-part-tariff-bill-run.spec.js
  cypress/integration/internal/billing/bills-tab.spec.js
  cypress/integration/internal/billing/license-transfer-to-new-billing-account.spec.js
  cypress/integration/internal/billing/mark-licence-for-supplementary-billing.spec.js
  cypress/integration/internal/billing/remove-individual-licence-from-bill.spec.js
  cypress/integration/internal/chargeinformation/change-user-permissions.spec.js
  cypress/integration/internal/chargeinformation/create-view-edit-delete-licence-agreements.spec.js
  cypress/integration/internal/chargeinformation/remove-charge-info-workflow.spec.js
  cypress/integration/internal/chargeinformation/sroc-charge-version-adjustments-option-no.spec.js
  cypress/integration/internal/chargeinformation/sroc-charge-version-adjustments-option-yes.spec.js
  cypress/integration/internal/chargeinformation/sroc-charge-version.spec.js
  cypress/integration/internal/chargeinformation/sroc-edit-submit-review-view-charge-version.spec.js
  cypress/integration/internal/chargeinformation/sroc-select-multiple-charge-version.spec.js
  cypress/integration/internal/returns/invite-licence-holders-submit-returns.spec.js
  cypress/integration/internal/returns/remind-licence-holders-submit-returns.spec.js
  cypress/integration/internal/returns/returns-status-view.spec.js
  cypress/integration/internal/returns/update-view-returns-status-of-a-licence.spec.js
  cypress/integration/internal/user/create-user.spec.js
  cypress/integration/internal/user/reset-password.spec.js
  cypress/integration/internal/user/search-for-licence.spec.js
  cypress/integration/internal/user/view-contacts.spec.js
  cypress/integration/internal/waa/gauging-stations-and-water-abstraction-alerts-mbod.spec.js
  cypress/integration/internal/waa/gauging-stations-and-water-abstraction-alerts.spec.js
  cypress/integration/internal/waa/paper-forms-flow.ci.spec.js
  cypress/plugins/index.js
  cypress/support/annual-bill-run.js
  cypress/support/commands.js
  cypress/support/common.js
  cypress/support/index.js
  cypress/support/notifications.js
  cypress/support/setup.js
  cypress/support/sroc-charge-version.js
  cypress/support/validation.js
  package-lock.json
  package.json
Labels: housekeeping

#2380 Add POST support to system proxy
  src/internal/modules/system-proxy/routes.js
Labels: enhancement

#2388 Fix licence number undefined in view
  src/internal/views/nunjucks/view-licences/licence.njk
Labels: bug

#2386 Fix name used for billing contact
  src/internal/modules/billing/controllers/bill-run.js
  src/internal/modules/billing/services/transactions-csv.js
  src/internal/views/nunjucks/billing/macros/invoices-table.njk
Labels: bug
