Repository DEFRA/water-abstraction-ui, pull requests merged in 2024-07, with the labels that each got.

#2581 Fix missed links to legacy view licence page
  src/internal/modules/returns/controllers/internal.js
  src/internal/modules/returns/controllers/view.js
Labels: bug

#2585 Update `water-abstraction-helpers` package
  package-lock.json
  package.json
Labels: dependencies

#2589 Update /workflow page to remove 'charge' elements
  src/internal/modules/charge-information/controllers/charge-information-workflow.js
  src/internal/modules/charge-information/pre-handlers.js
  src/internal/views/nunjucks/charge-information/workflow-tabs/review.njk
  src/internal/views/nunjucks/charge-information/workflow.njk
  src/internal/views/nunjucks/notifications/manage-tab.njk
  test/internal/modules/charge-information/controllers/charge-information-workflow.test.js
Labels: housekeeping
