Repository DEFRA/water-abstraction-ui, pull requests merged in 2024-11, with the labels that each got.

#2634 Update unit tests for `ENABLE_SYSTEM_LICENCE_VIEW` feature flag
  .github/workflows/ci.yml
  test/internal/modules/agreements/controller.test.js
  test/internal/modules/charge-information/controllers/charge-information.test.js
  test/internal/modules/charge-information/controllers/non-chargeable.test.js
  test/internal/modules/charge-information/controllers/view-charge-information.test.js
  test/internal/modules/returns/controllers/view.test.js
Labels: bug, housekeeping

#2638 Update missed links to new view monitoring station
  src/internal/modules/gauging-stations/controller.js
  src/internal/views/nunjucks/gauging-stations/new-tag-complete.njk
Labels: bug

#2639 Fix invalid link on tagging licence complete page
  src/internal/modules/gauging-stations/controller.js
  src/internal/views/nunjucks/gauging-stations/new-tag-complete.njk
Labels: bug

#2642 Upgrade node to v22
  .nvmrc
Labels: enhancement

#2643 Add feature flag and link for system returns notifications
  .env.example
  src/internal/config.js
  src/internal/modules/manage/lib/manage-nav.js
  test/internal/modules/manage/lib/manage-nav.test.js
Labels: enhancement

#2644 Add feature flag and link for system returns notifications
  .env.example
  src/internal/config.js
  src/internal/modules/manage/lib/manage-nav.js
  test/internal/modules/manage/lib/manage-nav.test.js
Labels: enhancement
